### PR TITLE
Create project.json file for firebaseopensource.com

### PR DESCRIPTION
**Pull request by samtstern**
@radi-cho this file is required to add this project to firebaseopensource.com!  Let me know if you have a better title to use.

### CODE REVIEW

**Comment by radi-cho** [comment]
I think the name is alright as it is :)

**Comment by samtstern** [comment]
@radi-cho ok once you merge this I'll add it to the site!

**Comment by radi-cho** [comment]
Thanks a lot! :)

**Comment by samtstern** [comment]
Added! https://github.com/firebase/firebaseopensource.com/commit/03b0d20ac9728a6b05da8712e4686914caf3b354

Your page will be live on the site within 24h

**Pull request merged**
